#pragma once

#include "NativeGameplayTags.h"

namespace MSGameplayTags
{
	/* Player Ability Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_DefaultAttack);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Blink);
	
	/* Player State Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Invincible);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Dead);

	/* Player Event Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_DefaultAttack);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Blink);

	/* Player Cooldown Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_Blink);

#pragma region Enemy Tag Section
	/*Enemy State Tags*/
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Idle);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Move);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Chase);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Attack);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Dead);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Spawn);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Groggy);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Phase2);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Pattern1);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Pattern2);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Pattern3);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Pattern4);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_PreventRotation);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_CoolDown);
	
	/*Enemy Ability Tags*/
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Idle);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Move);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Dead);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_NormalAttack);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Spawn);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Groggy);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Pattern1);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Pattern2);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Pattern3);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Pattern4);
	
	/*Enemy Tier Tags*/
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Tier_Normal);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Tier_Elite);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Tier_Boss);
	
	/*Enemy Event Tags*/
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_NormalAttack);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_HealthDepleted);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Death);         
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Groggy);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_PhaseChanged);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Idle);
#pragma  endregion
	
	/* Skill Ability Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Ability_IceSpear);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Ability_Lightning);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Ability_Tornado);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Ability_Explosion);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Ability_Fireball);

	/* Skill Event Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Event_IceSpear);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Event_Lightning);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Event_Tornado);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Event_Explosion);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Event_Fireball);
	
	/* Skill Upgrade Type Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Upgrade_Damage);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Upgrade_CoolTime);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Upgrade_ProjectileNum);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Upgrade_Penetration);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Upgrade_Range);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Upgrade_Duration);

	/* GameplayCue Tags */
	//MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HitFlash);
	
	/* Hit Result Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_Critical);

	/* Damage Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);


	/* Shared Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_DrawDamageNumber);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_DrawDamageNumber);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_Init);

	/* TEST Tags */
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TEST_Ability_HpIncrease);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TEST_Ability_HpDecrease);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TEST_Ability_MaxHpIncrease);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TEST_Ability_MaxHpDecrease);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TEST_Event_HpIncrease);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TEST_Event_HpDecrease);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TEST_Event_MaxHpIncrease);
	MAGESQUAD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TEST_Event_MaxHpDecrease);
}
